from MODULE import data_sr, generate
import os
try:
    from PyQt5 import QtCore, QtGui, QtWidgets
    from PyQt5.QtWidgets import *
    from PyQt5.QtCore import *

except ModuleNotFoundError:
    os.system('pip install pyqt5==5.15.4')


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(10, 10))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("DATA/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.train_neuro_page = QtWidgets.QTabWidget(self.centralwidget)
        self.train_neuro_page.setGeometry(QtCore.QRect(-2, -3, 805, 601))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.train_neuro_page.setFont(font)
        self.train_neuro_page.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));")
        self.train_neuro_page.setObjectName("train_neuro_page")
        self.generate = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.generate.setFont(font)
        self.generate.setObjectName("generate")
        self.text_neuro = QtWidgets.QPlainTextEdit(self.generate)
        self.text_neuro.setGeometry(QtCore.QRect(110, 40, 581, 401))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_neuro.setFont(font)
        self.text_neuro.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.text_neuro.setPlainText("")
        self.text_neuro.setObjectName("text_neuro")
        self.LOSHKA_AI_LABLE = QtWidgets.QLabel(self.generate)
        self.LOSHKA_AI_LABLE.setGeometry(QtCore.QRect(320, 0, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.LOSHKA_AI_LABLE.setFont(font)
        self.LOSHKA_AI_LABLE.setStyleSheet("")
        self.LOSHKA_AI_LABLE.setObjectName("LOSHKA_AI_LABLE")
        self.delete_btn = QtWidgets.QPushButton(self.generate)
        self.delete_btn.setGeometry(QtCore.QRect(601, 450, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("color: rgb(0, 0, 0);")
        self.delete_btn.setObjectName("delete_btn")
        self.generate_btn = QtWidgets.QPushButton(self.generate)
        self.generate_btn.setGeometry(QtCore.QRect(110, 450, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.generate_btn.setFont(font)
        self.generate_btn.setStyleSheet("color: rgb(0, 0, 0);")
        self.generate_btn.setObjectName("generate_btn")
        self.JxaxJ_lable = QtWidgets.QLabel(self.generate)
        self.JxaxJ_lable.setGeometry(QtCore.QRect(340, 520, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.JxaxJ_lable.setFont(font)
        self.JxaxJ_lable.setObjectName("JxaxJ_lable")
        self.label = QtWidgets.QLabel(self.generate)
        self.label.setGeometry(QtCore.QRect(430, 520, 41, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("DATA/icon/github_40_40.png"))
        self.label.setObjectName("label")
        self.train_neuro_page.addTab(self.generate, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.start_train_btn = QtWidgets.QPushButton(self.tab)
        self.start_train_btn.setGeometry(QtCore.QRect(350, 410, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.start_train_btn.setFont(font)
        self.start_train_btn.setMouseTracking(False)
        self.start_train_btn.setTabletTracking(False)
        self.start_train_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.start_train_btn.setStyleSheet("color: rgb(0, 0, 0);")
        self.start_train_btn.setObjectName("start_train_btn")
        self.loss_lable = QtWidgets.QLabel(self.tab)
        self.loss_lable.setGeometry(QtCore.QRect(-1, 0, 801, 41))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(11)
        self.loss_lable.setFont(font)
        self.loss_lable.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.loss_lable.setObjectName("loss_lable")
        self.neuro_swith_box = QtWidgets.QComboBox(self.tab)
        self.neuro_swith_box.setGeometry(QtCore.QRect(0, 42, 131, 21))
        self.neuro_swith_box.setObjectName("neuro_swith_box")
        self.neuro_swith_box.addItem("")
        self.console_lable = QtWidgets.QLabel(self.tab)
        self.console_lable.setGeometry(QtCore.QRect(-1, 506, 801, 51))
        font = QtGui.QFont()
        font.setFamily("MingLiU-ExtB")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.console_lable.setFont(font)
        self.console_lable.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.console_lable.setText("Если программа зависла - это нормально, после окончания обучения она восстановится")
        self.console_lable.setObjectName("console_lable")
        self.train_neuro_page.addTab(self.tab, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.label_2 = QtWidgets.QLabel(self.settings)
        self.label_2.setGeometry(QtCore.QRect(305, -15, 131, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.settings)
        self.label_3.setGeometry(QtCore.QRect(250, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lenght = QtWidgets.QSpinBox(self.settings)
        self.lenght.setGeometry(QtCore.QRect(320, 40, 101, 21))
        self.lenght.setMaximum(1000)
        self.lenght.setProperty("value", 100)
        self.lenght.setObjectName("lenght")
        self.apply_btn = QtWidgets.QPushButton(self.settings)
        self.apply_btn.setGeometry(QtCore.QRect(330, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.apply_btn.setFont(font)
        self.apply_btn.setStyleSheet("color: rgb(0, 0, 0);")
        self.apply_btn.setObjectName("apply_btn")
        self.reload_lable = QtWidgets.QLabel(self.settings)
        self.reload_lable.setGeometry(QtCore.QRect(410, 520, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.reload_lable.setFont(font)
        self.reload_lable.setObjectName("reload_lable")
        self.epochBox = QtWidgets.QSpinBox(self.settings)
        self.epochBox.setGeometry(QtCore.QRect(320, 75, 101, 21))
        self.epochBox.setMinimum(1)
        self.epochBox.setMaximum(100)
        self.epochBox.setProperty("value", 3)
        self.epochBox.setObjectName("lenght_2")
        self.label_4 = QtWidgets.QLabel(self.settings)
        self.label_4.setGeometry(QtCore.QRect(230, 75, 81, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.train_neuro_page.addTab(self.settings, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.train_neuro_page.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.lenght.setValue(data_sr.get_lenght()), self.epochBox.setValue(data_sr.get_train_epoch())

        self.add_function()

    def add_function(self):
        self.generate_btn.clicked.connect(lambda: self.genetete_text())
        self.delete_btn.clicked.connect(lambda: self.delete_text())
        self.apply_btn.clicked.connect(lambda: self.save_data(self.lenght.value(), self.epochBox.value()))
        self.start_train_btn.clicked.connect(lambda: self.train())

    def genetete_text(self):
        self.text_neuro.setPlainText(generate.generate_poems())

    def delete_text(self):
        self.text_neuro.setPlainText('')

    def save_data(self, lenght, train_epoch):
        self.reload_lable.setText('Что бы применить настройки - перезапустите приложение*')
        data_sr.save_data(lenght, train_epoch)

    def train(self):
        from MODULE import train_neuro
        train_neuro.train(self.epochBox.value())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LOSHKA AI"))
        self.LOSHKA_AI_LABLE.setText(_translate("MainWindow", "LOSHKA AI"))
        self.delete_btn.setText(_translate("MainWindow", "DELETE"))
        self.generate_btn.setText(_translate("MainWindow", "GENERATE"))
        self.JxaxJ_lable.setText(_translate("MainWindow", "JxaxJ"))
        self.train_neuro_page.setTabText(self.train_neuro_page.indexOf(self.generate), _translate("MainWindow", "Generate"))
        self.start_train_btn.setText(_translate("MainWindow", "START TRAIN"))
        self.loss_lable.setText(_translate("MainWindow", "Ваш прошлый loss - "))
        self.neuro_swith_box.setItemText(0, _translate("MainWindow", "Loshka_poems"))
        self.train_neuro_page.setTabText(self.train_neuro_page.indexOf(self.tab), _translate("MainWindow", "Train"))
        self.label_2.setText(_translate("MainWindow", "SETTINGS"))
        self.label_3.setText(_translate("MainWindow", "length"))
        self.apply_btn.setText(_translate("MainWindow", "APPLY"))
        self.reload_lable.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", "train epoch"))
        self.train_neuro_page.setTabText(self.train_neuro_page.indexOf(self.settings), _translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())