from MODULE import data_sr, generate
import os

try:
    from PyQt5 import QtCore, QtGui, QtWidgets
    from PyQt5.QtWidgets import *
    from PyQt5.QtCore import *

except ModuleNotFoundError:
    os.system('pip install pyqt5==5.15.4')


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(10, 10))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("DATA/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.main_page = QtWidgets.QTabWidget(self.centralwidget)
        self.main_page.setGeometry(QtCore.QRect(-2, -3, 805, 605))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.main_page.setFont(font)
        self.main_page.setStyleSheet(
            "color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
            "background-color: rgb(47, 47, 47);\n"
            "border-color: rgb(200, 200, 200);")
        self.main_page.setObjectName("main_page")
        self.generate = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.generate.setFont(font)
        self.generate.setObjectName("generate")
        self.text_neuro = QtWidgets.QPlainTextEdit(self.generate)
        self.text_neuro.setGeometry(QtCore.QRect(110, 40, 581, 401))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.text_neuro.setFont(font)
        self.text_neuro.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(68, 68, 68);\n"
                                      "border-radius: 10;\n"
                                      "")
        self.text_neuro.setObjectName("text_neuro")
        self.LOSHKA_AI_LABLE = QtWidgets.QLabel(self.generate)
        self.LOSHKA_AI_LABLE.setGeometry(QtCore.QRect(320, 5, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.LOSHKA_AI_LABLE.setFont(font)
        self.LOSHKA_AI_LABLE.setStyleSheet("border-radius: 15px;\n"
                                           "color: rgb(255, 255, 255);\n"
                                           "border: 0.5px solid rgb(255, 255, 255);")
        self.LOSHKA_AI_LABLE.setObjectName("LOSHKA_AI_LABLE")
        self.delete_btn = QtWidgets.QPushButton(self.generate)
        self.delete_btn.setGeometry(QtCore.QRect(561, 450, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("color: rgb(0, 0, 0);\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "border-radius: 20px;\n"
                                      "border: 0.5px solid;")
        self.delete_btn.setObjectName("delete_btn")
        self.generate_btn = QtWidgets.QPushButton(self.generate)
        self.generate_btn.setGeometry(QtCore.QRect(110, 450, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.generate_btn.setFont(font)
        self.generate_btn.setStyleSheet("color: rgb(0, 0, 0);\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "border-radius: 20px;\n"
                                        "border: 0.5px solid;")
        self.generate_btn.setObjectName("generate_btn")
        self.JxaxJ_lable = QtWidgets.QLabel(self.generate)
        self.JxaxJ_lable.setGeometry(QtCore.QRect(324, 520, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.JxaxJ_lable.setFont(font)
        self.JxaxJ_lable.setObjectName("JxaxJ_lable")
        self.git_icon = QtWidgets.QLabel(self.generate)
        self.git_icon.setGeometry(QtCore.QRect(412, 520, 41, 41))
        self.git_icon.setText("")
        self.git_icon.setPixmap(QtGui.QPixmap("DATA/icon/github_40_40.png"))
        self.git_icon.setObjectName("git_icon")
        self.main_page.addTab(self.generate, "")
        self.train_tab = QtWidgets.QWidget()
        self.train_tab.setObjectName("train_tab")
        self.start_train_btn = QtWidgets.QPushButton(self.train_tab)
        self.start_train_btn.setGeometry(QtCore.QRect(327, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.start_train_btn.setFont(font)
        self.start_train_btn.setMouseTracking(False)
        self.start_train_btn.setTabletTracking(False)
        self.start_train_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.start_train_btn.setStyleSheet("color: rgb(0, 0, 0);\n"
                                           "background-color: rgb(255, 255, 255);\n"
                                           "border-radius: 20px;\n"
                                           "border: 0.5px solid;")
        self.start_train_btn.setObjectName("start_train_btn")
        self.loss_lable = QtWidgets.QLabel(self.train_tab)
        self.loss_lable.setGeometry(QtCore.QRect(-1, 0, 805, 42))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(11)
        self.loss_lable.setFont(font)
        self.loss_lable.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(68, 68, 68);")
        self.loss_lable.setObjectName("loss_lable")
        self.neuro_swith_box = QtWidgets.QComboBox(self.train_tab)
        self.neuro_swith_box.setGeometry(QtCore.QRect(0, 42, 131, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.neuro_swith_box.setFont(font)
        self.neuro_swith_box.setStyleSheet("color: rgb(255, 255, 255);\n"
                                           "background-color: rgb(68, 68, 68);\n"
                                           "")
        self.neuro_swith_box.setObjectName("neuro_swith_box")
        self.neuro_swith_box.addItem("")
        self.console_lable = QtWidgets.QLabel(self.train_tab)
        self.console_lable.setGeometry(QtCore.QRect(-1, 506, 806, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.console_lable.setFont(font)
        self.console_lable.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "background-color: rgb(68, 68, 68);")
        self.console_lable.setObjectName("console_lable")
        self.main_page.addTab(self.train_tab, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.settings_lable = QtWidgets.QLabel(self.settings)
        self.settings_lable.setGeometry(QtCore.QRect(307, -10, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.settings_lable.setFont(font)
        self.settings_lable.setStyleSheet("color: rgb(255, 255, 255);")
        self.settings_lable.setObjectName("settings_lable")
        self.length = QtWidgets.QLabel(self.settings)
        self.length.setGeometry(QtCore.QRect(252, 43, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.length.setFont(font)
        self.length.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "")
        self.length.setObjectName("length")
        self.lenghtBox = QtWidgets.QSpinBox(self.settings)
        self.lenghtBox.setGeometry(QtCore.QRect(320, 50, 101, 21))
        self.lenghtBox.setStyleSheet("color: rgb(255, 255, 255);\n"
                                  "background-color: rgb(68, 68, 68);")
        self.lenghtBox.setMaximum(1000)
        self.lenghtBox.setProperty("value", 100)
        self.lenghtBox.setObjectName("lenghtBox")
        self.apply_btn = QtWidgets.QPushButton(self.settings)
        self.apply_btn.setGeometry(QtCore.QRect(330, 120, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.apply_btn.setFont(font)
        self.apply_btn.setStyleSheet("color: rgb(0, 0, 0);\n"
                                     "background-color: rgb(255, 255, 255);\n"
                                     "border-radius: 10px;\n"
                                     "border: 0.5px solid;\n"
                                     "")
        self.apply_btn.setObjectName("apply_btn")
        self.reload_lable = QtWidgets.QLabel(self.settings)
        self.reload_lable.setGeometry(QtCore.QRect(410, 520, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.reload_lable.setFont(font)
        self.reload_lable.setStyleSheet("color: rgb(255, 255, 255);")
        self.reload_lable.setText("")
        self.reload_lable.setObjectName("reload_lable")
        self.epochBox = QtWidgets.QSpinBox(self.settings)
        self.epochBox.setGeometry(QtCore.QRect(320, 85, 101, 21))
        self.epochBox.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "background-color: rgb(68, 68, 68);")
        self.epochBox.setMinimum(1)
        self.epochBox.setMaximum(100)
        self.epochBox.setProperty("value", 3)
        self.epochBox.setObjectName("train_epoch")
        self.train_epoch_lable = QtWidgets.QLabel(self.settings)
        self.train_epoch_lable.setGeometry(QtCore.QRect(208, 85, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.train_epoch_lable.setFont(font)
        self.train_epoch_lable.setStyleSheet("color: rgb(255, 255, 255);")
        self.train_epoch_lable.setObjectName("train_epoch_lable")
        self.chose_theme_box = QtWidgets.QComboBox(self.settings)
        self.chose_theme_box.setGeometry(QtCore.QRect(693, 0, 104, 22))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.chose_theme_box.setFont(font)
        self.chose_theme_box.setStyleSheet("color: rgb(255, 255, 255);\n"
                                           "background-color: rgb(68, 68, 68);")
        self.chose_theme_box.setObjectName("chose_theme_box")
        self.chose_theme_box.addItem("")
        self.chose_theme_box.addItem("")
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.main_page.addTab(self.settings, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_page.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_function()

        self.lenghtBox.setValue(data_sr.get_lenght())
        self.epochBox.setValue(data_sr.get_train_epoch())

    def add_function(self):
        self.generate_btn.clicked.connect(lambda: self.genetete_text())
        self.delete_btn.clicked.connect(lambda: self.delete_text())
        self.apply_btn.clicked.connect(lambda: self.save_data(lenght=self.lenghtBox.value(), train_epoch=self.epochBox.value(), theme='light' if self.chose_theme_box.currentText() == 'White theme' else 'dark'))
        self.start_train_btn.clicked.connect(lambda: self.train())

    def genetete_text(self):
        self.text_neuro.setPlainText(generate.generate_verses())

    def delete_text(self):
        self.text_neuro.setPlainText('')

    def save_data(self, lenght, train_epoch, theme):
        self.reload_lable.setText('Что бы применить настройки - перезапустите приложение*')
        data_sr.save_data(lenght, train_epoch, theme)

    def train(self):
        from MODULE import train_neuro
        train_neuro.train(self.epochBox.value())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LOSHKA AI"))
        self.text_neuro.setPlainText(_translate("MainWindow", ""))
        self.LOSHKA_AI_LABLE.setText(_translate("MainWindow", "LOSHKA AI"))
        self.delete_btn.setText(_translate("MainWindow", "DELETE"))
        self.generate_btn.setText(_translate("MainWindow", "GENERATE"))
        self.JxaxJ_lable.setText(_translate("MainWindow", "JxaxJ"))
        self.main_page.setTabText(self.main_page.indexOf(self.generate), _translate("MainWindow", "Generate"))
        self.start_train_btn.setText(_translate("MainWindow", "START TRAIN"))
        self.loss_lable.setText(_translate("MainWindow", "Ваш прошлый loss - "))
        self.neuro_swith_box.setItemText(0, _translate("MainWindow", "Loshka_poems"))
        self.console_lable.setText(_translate("MainWindow",
                                              "Если программа зависла - это нормально, после окончания обучения она восстановится"))
        self.main_page.setTabText(self.main_page.indexOf(self.train_tab), _translate("MainWindow", "Train"))
        self.settings_lable.setText(_translate("MainWindow", "SETTINGS"))
        self.length.setText(_translate("MainWindow", "length"))
        self.apply_btn.setText(_translate("MainWindow", "APPLY"))
        self.train_epoch_lable.setText(_translate("MainWindow", "train epoch"))
        self.chose_theme_box.setItemText(0, _translate("MainWindow", "Dark theme"))
        self.chose_theme_box.setItemText(1, _translate("MainWindow", "White theme"))
        self.main_page.setTabText(self.main_page.indexOf(self.settings), _translate("MainWindow", "Settings"))


def start():
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
